import type { PieceType, CellValue } from '@/lib/game/types';

export interface LessonStep {
  stepNumber: number;
  tip: string;
  subTip?: string;
  subTipColor?: 'cyan' | 'yellow' | 'red';
  neededPiece: PieceType;
  targetPosition: { x: number; y: number; rotation: 0 | 1 | 2 | 3 };
  allowedPieces?: PieceType[];
  successCondition: {
    type: 'place' | 'clear' | 'tspin' | 'tspin_double' | 'tspin_triple' | 'perfect_clear';
    minLines?: number;
  };
  feedbackSuccess: string;
  feedbackFail: string;
}

export interface Lesson {
  id: string;
  category: 'spins' | 'openers' | 'combos' | 'defense';
  title: string;
  description: string;
  difficulty: 'beginner' | 'intermediate' | 'advanced';
  orderIndex: number;
  steps: LessonStep[];
  initialBoard: CellValue[][];
  initialQueue: PieceType[];
  initialHold: PieceType | null;
}

const E = (): CellValue[] => Array(10).fill(0) as CellValue[];
const G = (hole: number): CellValue[] => {
  const row = Array(10).fill(8) as CellValue[];
  row[hole] = 0;
  return row;
};
const R = (...cells: number[]): CellValue[] => cells as CellValue[];

export const LESSONS: Lesson[] = [
  {
    id: 'tspin-single',
    category: 'spins',
    title: 'T-Spin Single',
    description:
      'Learn to rotate a T piece into a tight slot to score a T-Spin Single. The key is that your last move before lock must be a rotation.',
    difficulty: 'beginner',
    orderIndex: 0,
    initialBoard: [
      E(),
      E(),
      E(),
      E(),
      E(),
      E(),
      E(),
      E(),
      E(),
      E(),
      E(),
      E(),
      E(),
      E(),
      R(1, 1, 1, 0, 0, 0, 0, 1, 1, 1),
      R(1, 1, 1, 0, 0, 0, 0, 1, 1, 1),
      R(1, 1, 1, 1, 0, 1, 1, 1, 1, 1),
      R(1, 1, 1, 1, 0, 1, 1, 1, 1, 1),
      R(1, 1, 1, 1, 0, 1, 1, 1, 1, 1),
      R(1, 1, 1, 1, 0, 1, 1, 1, 1, 1),
    ],
    initialQueue: ['T', 'T', 'I', 'O', 'S', 'Z', 'J', 'L'],
    initialHold: null,
    steps: [
      {
        stepNumber: 1,
        tip: 'Step 1: Position T above the slot',
        subTip: 'Move T directly above the gap at column 4 and hard-drop it into position',
        subTipColor: 'cyan',
        neededPiece: 'T',
        targetPosition: { x: 3, y: 14, rotation: 2 },
        successCondition: { type: 'place' },
        feedbackSuccess: 'Good! Now the next T piece — rotate it into the slot.',
        feedbackFail: 'Move the T piece above the gap first.',
      },
      {
        stepNumber: 2,
        tip: 'Step 2: Rotate T into the slot — last move must be rotation',
        subTip: 'Move T near the slot, rotate it in as the final action, then Space to lock.',
        subTipColor: 'yellow',
        neededPiece: 'T',
        targetPosition: { x: 3, y: 17, rotation: 0 },
        successCondition: { type: 'tspin', minLines: 1 },
        feedbackSuccess: 'T-Spin Single! Perfect — rotation was your last move.',
        feedbackFail: 'No T-spin detected. Rotate T into the slot as the very last action before Space.',
      },
    ],
  },
  {
    id: 'tspin-double',
    category: 'spins',
    title: 'T-Spin Double',
    description: 'Set up a T-slot overhang, slide in, and rotate to clear 2 lines.',
    difficulty: 'beginner',
    orderIndex: 1,
    initialBoard: [
      E(),
      E(),
      E(),
      E(),
      E(),
      E(),
      E(),
      E(),
      E(),
      E(),
      E(),
      E(),
      E(),
      E(),
      R(0, 0, 0, 0, 0, 0, 0, 1, 1, 1),
      R(1, 0, 0, 0, 0, 0, 0, 1, 1, 1),
      R(1, 1, 0, 0, 0, 0, 1, 1, 1, 1),
      R(1, 1, 1, 0, 0, 0, 1, 1, 1, 1),
      R(1, 1, 1, 0, 0, 1, 1, 1, 1, 1),
      R(1, 1, 1, 1, 0, 1, 1, 1, 1, 1),
    ],
    initialQueue: ['T', 'T', 'S', 'Z', 'J', 'L', 'O', 'I'],
    initialHold: null,
    steps: [
      {
        stepNumber: 1,
        tip: 'Step 1: Slide the T piece into the overhang from the left',
        subTip: 'Move T all the way left then slide right under the overhang. Hard-drop with Space.',
        subTipColor: 'cyan',
        neededPiece: 'T',
        targetPosition: { x: 1, y: 16, rotation: 1 },
        successCondition: { type: 'place' },
        feedbackSuccess: 'Perfect position! Next T piece — rotate clockwise into the slot.',
        feedbackFail: 'Get the T piece under the overhang first.',
      },
      {
        stepNumber: 2,
        tip: 'Step 2: Rotate T clockwise into the slot — then Space',
        subTip: 'Rotation must be last: move near slot, rotate CW, then Space to lock.',
        subTipColor: 'yellow',
        neededPiece: 'T',
        targetPosition: { x: 1, y: 17, rotation: 0 },
        successCondition: { type: 'tspin_double' },
        feedbackSuccess: 'T-Spin Double! 4 lines of attack — rotation was last!',
        feedbackFail: 'Need a T-Spin Double. Last move must be a CW rotation into the slot.',
      },
    ],
  },
  {
    id: 'tspin-triple',
    category: 'spins',
    title: 'T-Spin Triple',
    description:
      'Rare and powerful — a T-Spin Triple clears 3 lines and sends 6 lines of attack. The T piece must be rotated (kicked) into the 3-high well as the last move.',
    difficulty: 'intermediate',
    orderIndex: 2,
    initialBoard: [
      E(),
      E(),
      E(),
      E(),
      E(),
      E(),
      E(),
      E(),
      E(),
      E(),
      E(),
      E(),
      E(),
      R(0, 0, 1, 1, 1, 1, 1, 1, 1, 1),
      R(0, 0, 0, 1, 1, 1, 1, 1, 1, 1),
      R(1, 0, 0, 0, 1, 1, 1, 1, 1, 1),
      R(1, 1, 0, 0, 0, 1, 1, 1, 1, 1),
      R(1, 1, 1, 0, 0, 0, 1, 1, 1, 1),
      R(1, 1, 1, 0, 0, 1, 1, 1, 1, 1),
      R(1, 1, 1, 1, 0, 1, 1, 1, 1, 1),
    ],
    initialQueue: ['T', 'T', 'T', 'T', 'T', 'T', 'T'],
    initialHold: null,
    steps: [
      {
        stepNumber: 1,
        tip: 'Step 1: Approach the well with T at rotation 3 (pointing left)',
        subTip: 'Move T to the right side of the well with rotation 3, then Space to drop.',
        subTipColor: 'cyan',
        neededPiece: 'T',
        targetPosition: { x: 3, y: 15, rotation: 3 },
        successCondition: { type: 'place' },
        feedbackSuccess: 'Good entry! Now use the next T to rotate into the well for the Triple.',
        feedbackFail: 'Position T above the well first.',
      },
      {
        stepNumber: 2,
        tip: 'Step 2: Rotate T into the 3-high well — T-Spin Triple!',
        subTip: 'Last move must be a rotation that kicks T into all 3 rows of the well.',
        subTipColor: 'yellow',
        neededPiece: 'T',
        targetPosition: { x: 3, y: 16, rotation: 1 },
        successCondition: { type: 'tspin_triple' },
        feedbackSuccess: 'T-Spin Triple! 6 lines of attack — masterful.',
        feedbackFail: 'T-Spin Triple not detected. Rotate T into the well as the final move.',
      },
    ],
  },
  {
    id: 'mini-tspin',
    category: 'spins',
    title: 'Mini T-Spin',
    description: 'Mini T-Spins are useful in pressure and combo routes.',
    difficulty: 'beginner',
    orderIndex: 3,
    initialBoard: [
      E(),
      E(),
      E(),
      E(),
      E(),
      E(),
      E(),
      E(),
      E(),
      E(),
      E(),
      E(),
      E(),
      E(),
      E(),
      E(),
      R(1, 1, 1, 1, 1, 1, 1, 0, 1, 1),
      R(1, 1, 1, 1, 1, 1, 0, 0, 1, 1),
      R(1, 1, 1, 1, 1, 1, 1, 0, 1, 1),
      R(1, 1, 1, 1, 1, 1, 1, 0, 1, 1),
    ],
    initialQueue: ['T', 'I', 'O', 'S', 'Z', 'J', 'L'],
    initialHold: null,
    steps: [
      {
        stepNumber: 1,
        tip: 'Step 1: Drop T into the right notch and rotate for mini',
        subTip: 'Rotate CW so T points right before lock.',
        subTipColor: 'cyan',
        neededPiece: 'T',
        targetPosition: { x: 6, y: 16, rotation: 3 },
        successCondition: { type: 'tspin', minLines: 1 },
        feedbackSuccess: 'Mini T-Spin complete.',
        feedbackFail: 'Rotate T into the notch. A slide-only clear will not count.',
      },
    ],
  },
  {
    id: 'perfect-clear',
    category: 'combos',
    title: 'Perfect Clear Basics',
    description: 'Fill the remaining gap and clear the board completely.',
    difficulty: 'intermediate',
    orderIndex: 4,
    initialBoard: [
      E(),
      E(),
      E(),
      E(),
      E(),
      E(),
      E(),
      E(),
      E(),
      E(),
      E(),
      E(),
      E(),
      E(),
      E(),
      E(),
      E(),
      R(1, 1, 0, 0, 0, 0, 0, 0, 1, 1),
      R(1, 1, 1, 0, 0, 0, 0, 1, 1, 1),
      R(1, 1, 1, 1, 0, 0, 1, 1, 1, 1),
    ],
    initialQueue: ['I', 'T', 'O', 'S', 'Z', 'J', 'L'],
    initialHold: null,
    steps: [
      {
        stepNumber: 1,
        tip: 'Step 1: Fill the central gap with I',
        subTip: 'Drop the I piece vertically into the center.',
        subTipColor: 'cyan',
        neededPiece: 'I',
        targetPosition: { x: 4, y: 16, rotation: 1 },
        successCondition: { type: 'perfect_clear' },
        feedbackSuccess: 'Perfect Clear! Huge value.',
        feedbackFail: 'You cleared lines but board is not empty yet.',
      },
    ],
  },
  {
    id: 'downstack-basics',
    category: 'defense',
    title: 'Downstacking Basics',
    description:
      'Garbage rows each have one hole. Drop a vertical I piece aligned with the hole to clear 4 rows at once. This drill uses uniform garbage — all holes at column 5.',
    difficulty: 'beginner',
    orderIndex: 5,
    initialBoard: [
      E(),
      E(),
      E(),
      E(),
      E(),
      E(),
      E(),
      E(),
      E(),
      E(),
      E(),
      E(),
      // 8 garbage rows, all holes at column 5 — easy to see the pattern
      G(5),
      G(5),
      G(5),
      G(5),
      G(5),
      G(5),
      G(5),
      G(5),
    ],
    initialQueue: ['I', 'I', 'I', 'I', 'I', 'I', 'I'],
    initialHold: null,
    steps: [
      {
        stepNumber: 1,
        tip: 'Step 1: Drop a vertical I piece into column 5 (the hole column)',
        subTip: 'All holes are at column 5. Place I vertically there — 4 rows clear at once!',
        subTipColor: 'cyan',
        neededPiece: 'I',
        targetPosition: { x: 3, y: 16, rotation: 1 },
        successCondition: { type: 'clear', minLines: 4 },
        feedbackSuccess: '4 rows cleared! Same hole column — do it again.',
        feedbackFail: 'Align the vertical I with column 5 (the hole). Drop it straight down.',
      },
      {
        stepNumber: 2,
        tip: 'Step 2: Clear the remaining 4 garbage rows',
        subTip: 'The holes are still at column 5. Same technique — vertical I, column 5.',
        subTipColor: 'yellow',
        neededPiece: 'I',
        targetPosition: { x: 3, y: 16, rotation: 1 },
        successCondition: { type: 'clear', minLines: 4 },
        feedbackSuccess: 'All garbage cleared! You can downstack efficiently.',
        feedbackFail: 'Drop the vertical I at column 5 to clear all remaining rows.',
      },
    ],
  },
  {
    id: '4-wide-combo',
    category: 'combos',
    title: '4-Wide Combo',
    description: 'Keep a 4-wide lane open and chain clears for combo pressure.',
    difficulty: 'intermediate',
    orderIndex: 6,
    initialBoard: [
      E(),
      E(),
      E(),
      E(),
      E(),
      E(),
      E(),
      E(),
      E(),
      E(),
      E(),
      E(),
      E(),
      R(0, 0, 0, 0, 1, 1, 1, 1, 1, 1),
      R(0, 0, 0, 0, 1, 1, 1, 1, 1, 1),
      R(0, 0, 0, 0, 1, 1, 1, 1, 1, 1),
      R(0, 0, 0, 0, 1, 1, 1, 1, 1, 1),
      R(0, 0, 0, 0, 1, 1, 1, 1, 1, 1),
      R(0, 0, 0, 0, 1, 1, 1, 1, 1, 1),
      R(0, 0, 0, 0, 1, 1, 1, 1, 1, 1),
    ],
    initialQueue: ['I', 'I', 'I', 'I', 'I', 'I', 'I'],
    initialHold: null,
    steps: [
      {
        stepNumber: 1,
        tip: 'Step 1: Drop I vertically into the 4-wide channel',
        subTip: 'Each clear maintains combo momentum.',
        subTipColor: 'cyan',
        neededPiece: 'I',
        targetPosition: { x: 0, y: 16, rotation: 1 },
        successCondition: { type: 'clear', minLines: 1 },
        feedbackSuccess: 'Combo continues. Keep chaining.',
        feedbackFail: 'Drop I in the left channel to clear and continue combo.',
      },
    ],
  },
  {
    id: 'tspin-double-drill',
    category: 'spins',
    title: 'T-Spin Double Drill',
    description:
      'Practice T-Spin Doubles back to back. The board has two stacked TSD setups — after your first clean TSD the second slot is revealed. Use rotation then Space to hard-drop and lock.',
    difficulty: 'intermediate',
    orderIndex: 7,
    initialBoard: [
      E(),
      E(),
      E(),
      E(),
      E(),
      E(),
      E(),
      E(),
      // Second TSD setup (revealed after first TSD clears the bottom)
      R(0, 0, 0, 0, 0, 0, 0, 1, 1, 1),
      R(1, 0, 0, 0, 0, 0, 0, 1, 1, 1),
      R(1, 1, 0, 0, 0, 0, 1, 1, 1, 1),
      R(1, 1, 1, 0, 0, 0, 1, 1, 1, 1),
      R(1, 1, 1, 0, 0, 1, 1, 1, 1, 1),
      R(1, 1, 1, 1, 0, 1, 1, 1, 1, 1),
      // First TSD setup (bottom)
      R(0, 0, 0, 0, 0, 0, 0, 1, 1, 1),
      R(1, 0, 0, 0, 0, 0, 0, 1, 1, 1),
      R(1, 1, 0, 0, 0, 0, 1, 1, 1, 1),
      R(1, 1, 1, 0, 0, 0, 1, 1, 1, 1),
      R(1, 1, 1, 0, 0, 1, 1, 1, 1, 1),
      R(1, 1, 1, 1, 0, 1, 1, 1, 1, 1),
    ],
    initialQueue: ['T', 'T', 'T', 'T', 'T', 'T', 'T', 'T'],
    initialHold: null,
    steps: [
      {
        stepNumber: 1,
        tip: 'Step 1: First T-Spin Double',
        subTip: 'Slide T under the left overhang and rotate CW into the slot. Press Space to lock.',
        subTipColor: 'cyan',
        neededPiece: 'T',
        targetPosition: { x: 1, y: 17, rotation: 0 },
        successCondition: { type: 'tspin_double' },
        feedbackSuccess: 'T-Spin Double! The second setup is now revealed.',
        feedbackFail: 'Need a T-Spin Double. Rotate T into the slot — last move must be a rotation.',
      },
      {
        stepNumber: 2,
        tip: 'Step 2: Second T-Spin Double',
        subTip: 'Same pattern — slide T left under the overhang and rotate into place.',
        subTipColor: 'yellow',
        neededPiece: 'T',
        targetPosition: { x: 1, y: 11, rotation: 0 },
        successCondition: { type: 'tspin_double' },
        feedbackSuccess: 'Two TSDs! Master-level consistency.',
        feedbackFail: 'Rotate T into the slot for a T-Spin Double.',
      },
    ],
  },
  {
    id: 'tspin-right-approach',
    category: 'spins',
    title: 'T-Spin Double (Right)',
    description:
      'T-Spin Doubles can be executed from both sides. This lesson teaches the right-approach TSD where you enter from the right and kick into the slot.',
    difficulty: 'intermediate',
    orderIndex: 8,
    initialBoard: [
      E(),
      E(),
      E(),
      E(),
      E(),
      E(),
      E(),
      E(),
      E(),
      E(),
      E(),
      E(),
      E(),
      E(),
      // Right-side staircase TSD (mirror of left approach)
      R(1, 1, 1, 0, 0, 0, 0, 0, 0, 0),
      R(1, 1, 1, 0, 0, 0, 0, 0, 1, 1),  // col 9=1 is the outside pillar after mirror
      R(1, 1, 1, 1, 0, 0, 0, 1, 1, 1),
      R(1, 1, 1, 1, 1, 0, 0, 1, 1, 1),
      R(1, 1, 1, 1, 1, 1, 0, 0, 1, 1),
      R(1, 1, 1, 1, 1, 1, 1, 0, 1, 1),
    ],
    initialQueue: ['T', 'T', 'I', 'O', 'S', 'Z', 'J', 'L'],
    initialHold: null,
    steps: [
      {
        stepNumber: 1,
        tip: 'Step 1: Position T rotation-3 above the right slot',
        subTip: 'Move T to the right side with rotation 3 (pointing left), then Space.',
        subTipColor: 'cyan',
        neededPiece: 'T',
        targetPosition: { x: 6, y: 16, rotation: 3 },
        successCondition: { type: 'place' },
        feedbackSuccess: 'Good placement! Next T — rotate CW into the slot.',
        feedbackFail: 'Move T to the right side gap.',
      },
      {
        stepNumber: 2,
        tip: 'Step 2: Rotate T clockwise into the right slot — last move!',
        subTip: 'Move T near the slot, rotate CW as the final action, then Space to lock.',
        subTipColor: 'yellow',
        neededPiece: 'T',
        targetPosition: { x: 6, y: 17, rotation: 0 },
        successCondition: { type: 'tspin_double' },
        feedbackSuccess: 'T-Spin Double from the right side! Excellent.',
        feedbackFail: 'Rotate T into the slot as the last move before Space.',
      },
    ],
  },
  {
    id: 'spin-freestyle',
    category: 'spins',
    title: 'Spin Freestyle',
    description:
      'An open practice room with T-spin setups pre-loaded. Complete any T-Spin (single, double, or triple) to advance each step. Six T pieces are queued — find the spin opportunities and execute them.',
    difficulty: 'beginner',
    orderIndex: 9,
    initialBoard: [
      E(),
      E(),
      E(),
      E(),
      E(),
      E(),
      E(),
      E(),
      E(),
      E(),
      E(),
      E(),
      E(),
      // Wide staircase with multiple spin opportunities
      R(0, 0, 0, 0, 0, 0, 0, 1, 1, 1),
      R(1, 0, 0, 0, 0, 0, 0, 1, 1, 1),
      R(1, 1, 0, 0, 0, 0, 1, 1, 1, 1),
      R(1, 1, 1, 0, 0, 0, 1, 1, 1, 1),
      R(1, 1, 1, 0, 0, 1, 1, 1, 1, 1),
      R(1, 1, 1, 1, 0, 1, 1, 1, 1, 1),
      R(1, 1, 1, 1, 1, 1, 1, 1, 1, 1),
    ],
    initialQueue: ['T', 'T', 'T', 'T', 'T', 'T'],
    initialHold: null,
    steps: [
      {
        stepNumber: 1,
        tip: 'Spin 1: Execute any T-Spin',
        subTip: 'Slide T into the staircase opening. Your last move before locking must be a rotation.',
        subTipColor: 'cyan',
        neededPiece: 'T',
        targetPosition: { x: 1, y: 17, rotation: 0 },
        successCondition: { type: 'tspin', minLines: 1 },
        feedbackSuccess: 'T-Spin! Next attempt.',
        feedbackFail: 'No T-spin detected. Rotate T into the gap — last move must be rotation.',
      },
      {
        stepNumber: 2,
        tip: 'Spin 2: Another T-Spin',
        subTip: 'The board has shifted — find the next opening and spin in.',
        subTipColor: 'cyan',
        neededPiece: 'T',
        targetPosition: { x: 1, y: 15, rotation: 0 },
        successCondition: { type: 'tspin', minLines: 1 },
        feedbackSuccess: 'T-Spin again! Getting consistent.',
        feedbackFail: 'Rotate T into the slot for a T-Spin.',
      },
      {
        stepNumber: 3,
        tip: 'Spin 3: Third T-Spin',
        subTip: 'Keep the habit — rotate LAST before locking.',
        subTipColor: 'yellow',
        neededPiece: 'T',
        targetPosition: { x: 1, y: 13, rotation: 0 },
        successCondition: { type: 'tspin', minLines: 1 },
        feedbackSuccess: 'Three T-Spins! You have the muscle memory now.',
        feedbackFail: 'Rotate into the slot. Last move = rotation.',
      },
    ],
  },
];

export function getLessonById(id: string): Lesson | undefined {
  return LESSONS.find((l) => l.id === id);
}

export function getLessonsByCategory(category: string): Lesson[] {
  return LESSONS.filter((l) => l.category === category).sort((a, b) => a.orderIndex - b.orderIndex);
}

export const CATEGORIES = [
  {
    id: 'spins',
    label: 'Spins',
    icon: '🌀',
    color: 'text-purple-400',
    border: 'border-purple-500/30',
    bg: 'bg-purple-500/5',
  },
  {
    id: 'openers',
    label: 'Openers',
    icon: '🚀',
    color: 'text-blue-400',
    border: 'border-blue-500/30',
    bg: 'bg-blue-500/5',
  },
  {
    id: 'combos',
    label: 'Combos',
    icon: '🔥',
    color: 'text-orange-400',
    border: 'border-orange-500/30',
    bg: 'bg-orange-500/5',
  },
  {
    id: 'defense',
    label: 'Defense',
    icon: '🛡️',
    color: 'text-green-400',
    border: 'border-green-500/30',
    bg: 'bg-green-500/5',
  },
] as const;
